/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiRevalidateRouteImport } from './routes/api.revalidate'
import { Route as ApiPreviewRouteImport } from './routes/api.preview'
import { Route as ApiExitPreviewRouteImport } from './routes/api.exit-preview'
import { Route as LocaleSignUpRouteImport } from './routes/$locale/sign-up'
import { Route as LocaleSignInRouteImport } from './routes/$locale/sign-in'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as LocaleProductsIndexRouteImport } from './routes/$locale/products/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleProductsSlugRouteImport } from './routes/$locale/products/$slug'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExitPreviewRoute = ApiExitPreviewRouteImport.update({
  id: '/api/exit-preview',
  path: '/api/exit-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSignUpRoute = LocaleSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignInRoute = LocaleSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsIndexRoute = LocaleProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsSlugRoute = LocaleProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/products/': typeof LocaleProductsIndexRoute
}
export interface FileRoutesByTo {
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/products': typeof LocaleProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/products/': typeof LocaleProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/$slug'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/products/$slug'
    | '/$locale/blog/'
    | '/$locale/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale/$slug'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/products/$slug'
    | '/$locale/blog'
    | '/$locale/products'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/$slug'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/products/$slug'
    | '/$locale/blog/'
    | '/$locale/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
  ApiExitPreviewRoute: typeof ApiExitPreviewRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exit-preview': {
      id: '/api/exit-preview'
      path: '/api/exit-preview'
      fullPath: '/api/exit-preview'
      preLoaderRoute: typeof ApiExitPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/sign-up': {
      id: '/$locale/sign-up'
      path: '/sign-up'
      fullPath: '/$locale/sign-up'
      preLoaderRoute: typeof LocaleSignUpRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-in': {
      id: '/$locale/sign-in'
      path: '/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleSignInRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products/': {
      id: '/$locale/products/'
      path: '/products'
      fullPath: '/$locale/products/'
      preLoaderRoute: typeof LocaleProductsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products/$slug': {
      id: '/$locale/products/$slug'
      path: '/products/$slug'
      fullPath: '/$locale/products/$slug'
      preLoaderRoute: typeof LocaleProductsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocaleSignInRoute: typeof LocaleSignInRoute
  LocaleSignUpRoute: typeof LocaleSignUpRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleProductsSlugRoute: typeof LocaleProductsSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleProductsIndexRoute: typeof LocaleProductsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSlugRoute: LocaleSlugRoute,
  LocaleSignInRoute: LocaleSignInRoute,
  LocaleSignUpRoute: LocaleSignUpRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleProductsSlugRoute: LocaleProductsSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleProductsIndexRoute: LocaleProductsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
  ApiExitPreviewRoute: ApiExitPreviewRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
