/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

type Def$a0a59591 = {
  /**
   * Map
   * 
   * The map of dynamic zones to slots.
   */
  'map': Array<{
    /**
     * Slug
     * 
     * The slug of the page as defined in Strapi.
     */
    'slug': string,
    /**
     * Sections
     * 
     * The list of the sections that should be connected.
     */
    'sections': Array<{
      /**
       * Croct slot
       * 
       * The ID of the slot as defined in Croct.
       */
      'slot': string,
      /**
       * Strapi component
       * 
       * The ID of the component as defined in Strapi.
       */
      'component': string,
    }>,
  }>,
};

declare module '@croct/plug/slot' {
  type DynamicZoneMapV1 = Def$a0a59591 & {'_component': 'dynamic-zone-map@1' | null};
  
  export interface VersionedSlotMap {
    'dynamic-zone-map': {
      latest: DynamicZoneMapV1,
      '1': DynamicZoneMapV1,
    };
  }
}

export {};